### PR TITLE
Fixes bug for Example.

### PR DESCRIPTION
**Pull request by iAugux**
Sorry...

I just double checked the OC code, and it was incorrect.
I've corrected the swift code. Please review it again. 😄

### CODE REVIEW

**Comment by ooper-shlab** [comment]
As far as I can see, the original Objective-C condition `!(isDirectory && [curFileName isEqualToString:@"Inbox"])` is exactly the equivalent to your first fix `!(isDirectory.boolValue && curFileName == "Inbox")`. Do you find anything wrong in the original Objective-C code?

**Comment by iAugux** [comment]
!(A && B) == !A || !B
The original OC is absolutely wrong.

What the author expects should be “not directory and not in Inbox folder”.

And the original OC code means “not in directory or not in Inbox folder".

I'm typing on my phone, sorry for the inconvenient.

**Comment by ooper-shlab** [comment]
I haven't tested that part of the original code till now, but the comment says: `ignore the "Inbox" folder`.
So, the author's intention seems to be: `ignore it if it is a folder and its name is "Inbox"`.

(Ignoring all folders makes sense, but ignoring all files or folders with name "Inbox" does not make sense.)

And as far as I tested `UIDocumentInteractionController` does not cause error when its `url` property is set to a folder URL.
Though `UIDocumentInteractionController` shows folders as of type `public.data`, and detail view does not show any information about the folder.

Thus, I'm not sure if it is an intended feature or just a bug. In such cases, I have a policy -- keep my repository just a translation of the original sample code.
So, I do not merge this second fix into my repository.

But, anyway, your info is really helpful and I have learnt many things from it. And no worry, I felt nothing inconvenient with your posts. Thanks.

**Comment by iAugux** [comment]
Sorry for the delay.

Your point is very reasonable. And the ambiguity is only in the demo project, so let's just ignore it.

**Comment by ooper-shlab** [comment]
Thanks for your comment. I really appreciate all your effort to contribute.

**Pull request closed without merging**
